# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1233, 822)
        Form.setStyleSheet("background-color: rgb(26, 22, 31);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.statusBar = QtWidgets.QFrame(Form)
        self.statusBar.setMinimumSize(QtCore.QSize(600, 35))
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.statusBar.setStyleSheet("border-top: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:0.488029 rgba(255, 255, 255, 255), stop:1 rgba(26, 22, 31, 0));")
        self.statusBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusBar.setObjectName("statusBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.statusBar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addWidget(self.statusBar, 4, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(420, 570))
        self.frame.setMaximumSize(QtCore.QSize(420, 570))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ampelFrame = QtWidgets.QFrame(self.frame)
        self.ampelFrame.setGeometry(QtCore.QRect(10, -10, 400, 550))
        self.ampelFrame.setMinimumSize(QtCore.QSize(400, 550))
        self.ampelFrame.setMaximumSize(QtCore.QSize(400, 550))
        self.ampelFrame.setStyleSheet("QFrame#ampelFrame{\n"
"border-image: url(:/ampel/ampelphasen-zeiten-programmieren-arduino.png);\n"
"background:none;\n"
"}")
        self.ampelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ampelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ampelFrame.setObjectName("ampelFrame")
        self.fussGelb = QtWidgets.QLabel(self.frame)
        self.fussGelb.setGeometry(QtCore.QRect(270, 150, 81, 71))
        self.fussGelb.setStyleSheet("background-color: rgb(47, 40, 56);")
        self.fussGelb.setText("")
        self.fussGelb.setObjectName("fussGelb")
        self.fussRot = QtWidgets.QLabel(self.frame)
        self.fussRot.setGeometry(QtCore.QRect(270, 60, 81, 81))
        self.fussRot.setStyleSheet("background-color: rgb(47, 40, 56);")
        self.fussRot.setText("")
        self.fussRot.setObjectName("fussRot")
        self.ampelRot = QtWidgets.QLabel(self.frame)
        self.ampelRot.setGeometry(QtCore.QRect(70, 20, 81, 71))
        self.ampelRot.setStyleSheet("background-color: rgb(47, 40, 56);")
        self.ampelRot.setText("")
        self.ampelRot.setObjectName("ampelRot")
        self.ampelGelb = QtWidgets.QLabel(self.frame)
        self.ampelGelb.setGeometry(QtCore.QRect(70, 110, 81, 71))
        self.ampelGelb.setStyleSheet("background-color: rgb(47, 40, 56);")
        self.ampelGelb.setText("")
        self.ampelGelb.setObjectName("ampelGelb")
        self.ampelGruen = QtWidgets.QLabel(self.frame)
        self.ampelGruen.setGeometry(QtCore.QRect(70, 190, 81, 71))
        self.ampelGruen.setStyleSheet("background-color: rgb(47, 40, 56);")
        self.ampelGruen.setText("")
        self.ampelGruen.setObjectName("ampelGruen")
        self.ampel_taster = QtWidgets.QPushButton(self.frame)
        self.ampel_taster.setGeometry(QtCore.QRect(270, 320, 90, 80))
        self.ampel_taster.setMinimumSize(QtCore.QSize(90, 80))
        self.ampel_taster.setMaximumSize(QtCore.QSize(90, 80))
        self.ampel_taster.setStyleSheet("QPushButton{\n"
"border:2px solid \"white\";\n"
"border-radius:50px;\n"
"color: \"white\";\n"
"    background-color: rgb(26, 22, 31);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(47, 40, 56);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(255, 218, 8);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ampel_taster.setObjectName("ampel_taster")
        self.ampelGruen.raise_()
        self.ampelGelb.raise_()
        self.fussGelb.raise_()
        self.fussRot.raise_()
        self.ampelRot.raise_()
        self.ampelFrame.raise_()
        self.ampel_taster.raise_()
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(420, 140))
        self.frame_2.setMaximumSize(QtCore.QSize(420, 140))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.r_taster = QtWidgets.QPushButton(self.frame_2)
        self.r_taster.setMinimumSize(QtCore.QSize(100, 100))
        self.r_taster.setMaximumSize(QtCore.QSize(100, 100))
        self.r_taster.setStyleSheet("QPushButton{\n"
"border:2px solid \"white\";\n"
"border-radius:50px;\n"
"color: \"white\";\n"
"    background-color: rgb(26, 22, 31);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(47, 40, 56);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(255, 85, 79);\n"
"}")
        self.r_taster.setObjectName("r_taster")
        self.horizontalLayout.addWidget(self.r_taster)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.s_taster = QtWidgets.QPushButton(self.frame_2)
        self.s_taster.setMinimumSize(QtCore.QSize(100, 100))
        self.s_taster.setMaximumSize(QtCore.QSize(100, 100))
        self.s_taster.setStyleSheet("QPushButton{\n"
"border:2px solid \"white\";\n"
"border-radius:50px;\n"
"color: \"white\";\n"
"    background-color: rgb(26, 22, 31);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(47, 40, 56);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(123, 255, 160);\n"
"    color: rgb(0,0,0);\n"
"}")
        self.s_taster.setObjectName("s_taster")
        self.horizontalLayout.addWidget(self.s_taster)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.toolBar = QtWidgets.QFrame(Form)
        self.toolBar.setMinimumSize(QtCore.QSize(600, 35))
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.toolBar.setStyleSheet("border-top: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:0.488029 rgba(255, 255, 255, 255), stop:1 rgba(26, 22, 31, 0));")
        self.toolBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBar.setObjectName("toolBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.toolBar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout.addWidget(self.toolBar, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.plainLay = QtWidgets.QFrame(Form)
        self.plainLay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainLay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plainLay.setObjectName("plainLay")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.plainLay)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.plainLay, 1, 1, 3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ampel_taster.setText(_translate("Form", "Taster"))
        self.r_taster.setText(_translate("Form", "R-Taster"))
        self.s_taster.setText(_translate("Form", "S-Taster"))

import imgages.img
